CREATE DATABASE IF NOT EXISTS lms_user_db;
CREATE DATABASE IF NOT EXISTS lms_course_db;
CREATE DATABASE IF NOT EXISTS lms_assessment_db;
CREATE DATABASE IF NOT EXISTS lms_notification_db;
CREATE DATABASE IF NOT EXISTS lms_attendance_db;
CREATE DATABASE IF NOT EXISTS lms_leave_db;
